# Generated by Django 3.1.5 on 2021-01-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20210112_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='', upload_to='cliente_fotos'),
            preserve_default=False,
        ),
    ]
